### ISSUE TITLE
connection to JLR servers broken again

### ISSUE THREAD

**Issue by shegnauer** [ardevd/jlrpy#122]
In device registration I get this error since about noon CEST today:

> jlr.js:823  Uncaught TypeError: Cannot read properties of null (reading 'userId')
>     at jlr.js:823:31
>     at req.onreadystatechange (jlr.js:760:11)
> 

and follow-up errors from my proxy. It was working as expected this morning.
Also, I noted the offical JLR app is now at version 1.8.1 - that one works as expected.

Edit: jlr.js is based on jlrpy 1.6.0, where it does also not connect anymore (no access to logs currently). WattCat is also not working anymore.

**Comment by merc5555** [comment]
Same issue 🙁

**Comment by rzumbuehl** [comment]
Thanks a lot!

**Comment by kkennedyuk** [comment]
Thank you so much for this - can I ask how are you determining the new headers to use? :-)

**Comment by pmharris77** [comment]
> Thank you so much for this - can I ask how are you determining the new headers to use? :-)

Presumably by capturing the HTTP requests from the android app?

**Comment by ardevd** [comment]
> Thank you so much for this - can I ask how are you determining the new headers to use? :-)

Correct. A combination of static and dynamic analysis.

**Comment by zwcall** [comment]
> > Thank you so much for this - can I ask how are you determining the new headers to use? :-)
> 
> Correct. A combination of static and dynamic analysis.

Hi ! you succeeded !
Since they updated it I tried to write the fix in PR but I didn't succeed. I have a rooted phone (magisk,lsposed,frida) and the app crashes on startup, I suppose it's due to the isolated process in the background which must behave like a watchdog?
would you be open to discussion please? I would like to understand my mistake 
thanks you again !
